favicon:
  enable: true
  icon: /favicon.ico
  touch_icon: /images/apple-touch-icon.png

avatar:
  path: /

prevnext:
  enable: true

link: 
  -
    name: archives
    icon: archive
    path: /archives/
  -
    name: github
    icon: github
    path: https://github.com/chris114782
    target: _blank
  -
    name: instagram
    icon: instagram
    path: https://www.instagram.com/fatcheezslim/
    target: _blank
  -
    name: feed
    icon: rss
    path: /atom.xml
    target: _blank


footer:
  -
    name: Favicon graphics by Twitter
    path: /assets/favicon-about.txt

search:
  enable: false
  placeholder: 
