favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

avatar:
  author_photo: /images/avatar.png
  author_nickname: Chris
  path: /

prevnext:
  enable: true

link: 
  -
    name: archives
    icon: mdi-bookmark
    path: /archives/
  -
    name: github
    icon: mdi-github
    path: https://github.com/cstretton
    target: _blank
  -
    name: email
    icon: mdi-at
    path: mailto:chris@stretton.xyz 
  -
    name: instagram
    icon: mdi-instagram
    path: https://www.instagram.com/cheezykins/
    target: _blank
  -
    name: feed
    icon: mdi-rss
    path: /atom.xml
    target: _blank


footer:
  -
    name: Copyright © Chris Stretton

search:
  enable: false
  placeholder: 
