favicon:
  enable: true
  icon: /images/favicon.ico
  touch_icon: /images/apple-touch-icon.png

avatar:
  path: /

prevnext:
  enable: true

link: 
  -
    name: archives
    icon: mdi-bookmark
    path: /archives/
  -
    name: github
    icon: mdi-github
    path: https://github.com/cstretton
    target: _blank
  -
    name: email
    icon: mdi-at
    path: mailto:chris@stretton.xyz 
  -
    name: instagram
    icon: mdi-instagram
    path: https://www.instagram.com/cheezykins/
    target: _blank
  -
    name: feed
    icon: mdi-rss
    path: /atom.xml
    target: _blank


footer:
  -
    name: Copyright © Chris Stretton
  -
    name: Favicon graphics by Twitter
    path: /assets/favicon-about.txt

search:
  enable: false
  placeholder: 
